config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  	sessions: 'users/sessions',
  	registatrations: 'users/registrations'
  }

  root "shootouts#index"
  get "/pages/about", "pages#show"
  resources :microphones, except: [:edit, :update] 
  resources :shootouts, except: [:edit, :update]
  resources :manufacturers, :instruments, :users
  resources :fav_shootouts, only: :create

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fav_shootout.rb
class FavShootout < ApplicationRecord
  belongs_to :user
  belongs_to :shootout
end

app/models/instrument.rb
class Instrument < ApplicationRecord
	has_many :shootouts
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	extend FriendlyId
  		friendly_id :name, use: :slugged
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
	has_many :microphones
	has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
	extend FriendlyId
  		friendly_id :name, use: :slugged
end

app/models/microphone.rb
class Microphone < ApplicationRecord
	belongs_to :manufacturer
	has_many :shootout_microphones
	has_many :shootouts, through: :shootout_microphones
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	extend FriendlyId
  		friendly_id :model, use: :slugged
end

app/models/shootout.rb
class Shootout < ApplicationRecord
	has_many :shootout_microphones, inverse_of: :shootout
	has_many :microphones, through: :shootout_microphones
	has_many :fav_shootouts
	belongs_to :instrument
	belongs_to :user
	accepts_nested_attributes_for :shootout_microphones, allow_destroy: true
end

app/models/shootout_microphone.rb
class ShootoutMicrophone < ApplicationRecord
  belongs_to :shootout, inverse_of: :shootout_microphones
  belongs_to :microphone
  has_attached_file :audio
  validates_attachment_size :audio, :less_than => 3.megabytes
  validates_attachment_content_type :audio, :content_type => [ 'audio/wav', 'audio/mpeg', 'audio/mp3']
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, :email, presence: true
  extend FriendlyId
  	friendly_id :username, use: :slugged
  has_many :shootouts
  has_many :fav_shootouts
end

app/controllers/intro_controller.rb
class IntroController < ApplicationController
	def show
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def show
		render template: "pages/about"
	end	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.friendly.find(params[:id])
		@instruments = @user.shootouts.each.map(&:instrument).uniq.sort_by &:name
		shootout_mics = @user.shootouts.each.map(&:shootout_microphones).flatten
		@microphones = shootout_mics.each.map(&:microphone).uniq.sort_by &:manufacturer
		@fav_shootouts = @user.fav_shootouts.each.map(&:shootout)
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    messages = resource.errors.full_messages.map { |msg| content_tag(:p, msg) }
  end
end

app/helpers/fav_shootouts_helper.rb
module FavShootoutsHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/intro_helper.rb
module IntroHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/microphones_helper.rb
module MicrophonesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shootouts_helper.rb
module ShootoutsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/intro/show.html.erb
<div class="fullscreen-bg">
<!-- 	<video class="responsive-video fullscreen-bg-video", autoplay: true, loop: true, id="intro-video">
    <source src="intro.mov" type="video/mp4">
  </video> -->

	<%= video_tag("intro.mov", loop: true, muted: true, autoplay: true, class: "fullscreen-bg-video responsive-video", id: "intro-video") %>
	<div id="intro-text-wrapper">
		<div id="intro-text-box">
			<div id="intro-text">
				<div id="intro-top">
					<h1 id="intro-header">Mic Shootout</h1>
					<%= link_to "Enter", shootouts_path, class: "btn", id: "enter-button" %>
				</div>
				<p> Lorem ipsum dolor sit amet, consectetur adipisicing 	elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
				</p>
			</div>

		</div>
	</div>
</div>