config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  	sessions: 'users/sessions',
  	registatrations: 'users/registrations'
  }

  root "shootouts#index"
  get "/pages/about", "pages#show"
  resources :microphones, except: [:edit, :update] 
  resources :shootouts, except: [:edit, :update]
  resources :manufacturers, :instruments, :users
  resources :fav_shootouts, only: :create

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fav_shootout.rb
class FavShootout < ApplicationRecord
  belongs_to :user
  belongs_to :shootout
end

app/models/instrument.rb
class Instrument < ApplicationRecord
	has_many :shootouts
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	extend FriendlyId
  		friendly_id :name, use: :slugged
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
	has_many :microphones
	has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
	extend FriendlyId
  		friendly_id :name, use: :slugged
end

app/models/microphone.rb
class Microphone < ApplicationRecord
	belongs_to :manufacturer
	has_many :shootout_microphones
	has_many :shootouts, through: :shootout_microphones
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	extend FriendlyId
  		friendly_id :model, use: :slugged
end

app/models/shootout.rb
class Shootout < ApplicationRecord
	has_many :shootout_microphones, inverse_of: :shootout
	has_many :microphones, through: :shootout_microphones
	has_many :fav_shootouts
	belongs_to :instrument
	belongs_to :user
	accepts_nested_attributes_for :shootout_microphones, allow_destroy: true
end

app/models/shootout_microphone.rb
class ShootoutMicrophone < ApplicationRecord
  belongs_to :shootout, inverse_of: :shootout_microphones
  belongs_to :microphone
  has_attached_file :audio
  validates_attachment_size :audio, :less_than => 3.megabytes
  validates_attachment_content_type :audio, :content_type => [ 'audio/wav', 'audio/mpeg', 'audio/mp3']
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, :email, presence: true
  extend FriendlyId
  	friendly_id :username, use: :slugged
  has_many :shootouts
  has_many :fav_shootouts
end

app/controllers/intro_controller.rb
class IntroController < ApplicationController
	def show
	end
end

app/controllers/microphones_controller.rb
class MicrophonesController < ApplicationController

	def index
	end
	def show
		@microphone = Microphone.friendly.find(params[:id])
	end
	def new
	end
	def create
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def show
		render template: "pages/about"
	end	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.friendly.find(params[:id])
		@instruments = @user.shootouts.each.map(&:instrument).uniq.sort_by &:name
		shootout_mics = @user.shootouts.each.map(&:shootout_microphones).flatten
		@microphones = shootout_mics.each.map(&:microphone).uniq.sort_by &:manufacturer
		@fav_shootouts = @user.fav_shootouts.each.map(&:shootout)
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    messages = resource.errors.full_messages.map { |msg| content_tag(:p, msg) }
  end
end

app/helpers/fav_shootouts_helper.rb
module FavShootoutsHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/intro_helper.rb
module IntroHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/microphones_helper.rb
module MicrophonesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shootouts_helper.rb
module ShootoutsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/microphones/show.html.erb
<div class="container mic-show-container">
	<div class="row mic-info-row">
		<div class="mic-info-image col m3">
			<%= image_tag @microphone.image.url, class: "responsive-img shootout-mic-image" %>
		</div>
		<div class="mic-info-spec col m9">
			<h5><%= @microphone.manufacturer.name %> <%= @microphone.model %></h5>
			<table>
			  <tr>
			    <th class="mic-table-header">Type:</th>
			    <td class="mic-table-data"><%= @microphone.kind %></td>
			  </tr>
			  <tr>
			    <th class="mic-table-header">Phantom:</th>
			    <td class="mic-table-data"><% if @microphone.phantom %>Yes<% else %>No<% end %></td>
			  </tr>
			  <tr>
			    <th class="mic-table-header">Polar Pattern:</th>
			    <td class="mic-table-data"><%= @microphone.polar_pattern %></td>
			  </tr>
	  		  <tr>
			    <th class="mic-table-header">Spec Sheet (<%= @microphone.manufacturer.name %>):</th>
			    <td class="mic-table-data"><%= @microphone.spec_sheet %></td>
			  </tr>
			</table>
		</div>
	</div>
	<div class="row">
		<p class="center manu-info-link">More microphones by 
			<%= link_to @microphone.manufacturer.name, manufacturer_path(@microphone.manufacturer)  %>
		</p>	
	</div>
</div>

<h5 id="index-shootout-header" class="left-align index-section-header">Shootouts</h5><hr class="index-section-hr">

<% if @microphone.shootouts.count === 0 %>
	<div class="container center no-shootout-msg">
		<div>Sorry, we do not have any shootouts available for this microphone.</div>
		<% if current_user  %>
			<div>Please be the first to post one <%= link_to 'here', new_shootout_path %>!</div>
		<% else  %>
			<div>Please log in <%= link_to 'here', new_user_session_path %> to post our first!</div>
		<% end  %>
	</div>
<% else  %>
	<% @microphone.shootouts.each do |shootout|  %>
		<%= render 'partials/shootout_list', :shootout => shootout %>
	<% end  %>
<% end  %>