config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  	sessions: 'users/sessions',
  	registatrations: 'users/registrations'
  }

  root "shootouts#index"
  get "/pages/about", "pages#show"
  resources :microphones, except: [:edit, :update] 
  resources :shootouts, except: [:edit, :update]
  resources :manufacturers, :instruments, :users
  resources :fav_shootouts, only: :create

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fav_shootout.rb
class FavShootout < ApplicationRecord
  belongs_to :user
  belongs_to :shootout
end

app/models/instrument.rb
class Instrument < ApplicationRecord
	has_many :shootouts
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	extend FriendlyId
  		friendly_id :name, use: :slugged
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
	has_many :microphones
	has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
	extend FriendlyId
  		friendly_id :name, use: :slugged
end

app/models/microphone.rb
class Microphone < ApplicationRecord
	belongs_to :manufacturer
	has_many :shootout_microphones
	has_many :shootouts, through: :shootout_microphones
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	extend FriendlyId
  		friendly_id :model, use: :slugged
end

app/models/shootout.rb
class Shootout < ApplicationRecord
	has_many :shootout_microphones, inverse_of: :shootout
	has_many :microphones, through: :shootout_microphones
	has_many :fav_shootouts
	belongs_to :instrument
	belongs_to :user
	accepts_nested_attributes_for :shootout_microphones, allow_destroy: true
end

app/models/shootout_microphone.rb
class ShootoutMicrophone < ApplicationRecord
  belongs_to :shootout, inverse_of: :shootout_microphones
  belongs_to :microphone
  has_attached_file :audio
  validates_attachment_size :audio, :less_than => 3.megabytes
  validates_attachment_content_type :audio, :content_type => [ 'audio/wav', 'audio/mpeg', 'audio/mp3']
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, :email, presence: true
  extend FriendlyId
  	friendly_id :username, use: :slugged
  has_many :shootouts
  has_many :fav_shootouts
end

app/controllers/intro_controller.rb
class IntroController < ApplicationController
	def show
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def show
		render template: "pages/about"
	end	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.friendly.find(params[:id])
		@instruments = @user.shootouts.each.map(&:instrument).uniq.sort_by &:name
		shootout_mics = @user.shootouts.each.map(&:shootout_microphones).flatten
		@microphones = shootout_mics.each.map(&:microphone).uniq.sort_by &:manufacturer
		@fav_shootouts = @user.fav_shootouts.each.map(&:shootout)
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    messages = resource.errors.full_messages.map { |msg| content_tag(:p, msg) }
  end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/intro_helper.rb
module IntroHelper
end

app/helpers/microphones_helper.rb
module MicrophonesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shootouts_helper.rb
module ShootoutsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mic Drop</title>
    <%= csrf_meta_tags %>
    <link rel="icon" href="http://icons.iconarchive.com/icons/icons8/windows-8/128/Music-Microphone-2-icon.png">

	<!-- Compiled and minified CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!--   Google Fonts -->  
  <link href="https://fonts.googleapis.com/css?family=Bungee+Inline" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	<!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
            
  </head>

  <body>

  <div class="navbar-fixed">
    <nav class="main-nav">
      <div class="nav-wrapper">
        <%= link_to "MIC DROP", root_path, class: "brand-logo" %>
        <% if current_user %>
          <%= render 'partials/user_dropdown', :user => current_user %>
        <% else  %>
          <%= render 'partials/guest_dropdown' %>
        <% end  %>
        <div class="hide-on-med-and-down">
          <%= link_to "Manufacturers", manufacturers_path, class: "header-nav-item" %>
          <i class="material-icons header-nav-item">store</i>
          <%= link_to "Instruments", instruments_path, class: "header-nav-item" %>
          <i class="material-icons header-nav-item">queue_music</i>
        </div>
      </div>
    </nav>
  </div>
  <div class="devise-error">
    <%- flash.each do |name, msg| -%>
       <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    <%- end -%> 
  </div>  
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="fullscreen-bg">
	<%= video_tag("intro.mov", loop: true, muted: true, autoplay: true, class: "fullscreen-bg-video", id: "intro-video") %>
	<div id="intro-text-wrapper">
		<div id="about-text-box">
			<div id="intro-top">
				<h3 id="intro-header">Mic Drop</h3>
				<h5>Your Resource for Microphone Shootouts</h5>
			</div>
			<p> Created by Web Developer and Audio Engineer, Christopher Chan, to help fellow recording engineers
				better understand the equipment they are looking to use or purchase. Currently in beta-testing, this
				site will be experiencing on-going changes without warning.
			</p>
		</div>
	</div>
	<div class="option-row hide-on-large-only mic-drop-font" id="option-row-about">
			<%= link_to "Instruments", instruments_path, class: "option-btn" %>
			<%= link_to "Manufacturers", manufacturers_path, class: "option-btn" %>
		</div>
</div>

app/views/partials/_guest_dropdown.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to 'Log In', new_user_session_path %></li>
  <li><%= link_to "Sign Up", new_user_registration_path %></li>
  <li class="divider"></li>
  <li><%= link_to 'About', pages_about_path %></li>
</ul>

<ul id="nav-mobile" class="right">
	<li><i class="tiny material-icons hide-on-small-only person-icon">perm_identity</i></li>
  <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Guest<i class="material-icons right">arrow_drop_down</i></a></li>
</ul>

app/views/partials/_instruments_list.html.erb
<div class="row center index-section-row">
	<h5 class="left-align index-section-header mobile-less-top">Instruments</h5><hr class="index-section-hr">
	<div class="owl-carousel col">
	<% @instruments.each do |instrument|  %>
		<%= link_to(instrument) do %>
		<div class="instrument-index-img-div instrument-index-img-div-small" style="background:url('<%= instrument.image.url %>')">
			<p><%= instrument.name %></p>
		</div>
		<% end  %>
	<% end  %>
	</div>
</div>

app/views/partials/_manufacturers_list.html.erb
<div class="row center index-section-row manu-row">
	<h5 class="left-align index-section-header">Manufacturers</h5><hr class="index-section-hr">
	<div class="owl-carousel col">
		<% @manufacturers.each do |manufacturer|  %>
			<%= link_to(manufacturer) do %>
			<div class="manu-img-div item">
				<%= image_tag manufacturer.logo.url, class: "responsive-img manu-img" %>
			</div>
			<% end  %>
		<% end  %>
	</div>
</div>

app/views/partials/_new_shootout_form.html.erb
    <div class="row new-shootout-field" id="new-shootout-4" disabled="true">
        <%= f.fields_for :shootout_microphones, ShootoutMicrophone.new, html: { multipart: true } do |builder| %>
          <div class="input-field col s6">
            <i class="material-icons prefix">mic</i>
            <%= builder.select :microphone_id, @microphones.collect { |mic| [ mic.manufacturer.name + " " + mic.model, mic.id ] }, prompt: 'Choose a Mic'  %>
          </div>
          <div class="input-field col s5">
            <i class="material-icons prefix">hearing</i>
            <%= builder.file_field :audio %>
          </div>
          <div class="col s1">
            <button class="remove-shootout-btn">X</button>
          </div>
        <% end %>
    </div>

    <div class="row new-shootout-field" id="new-shootout-5" disabled="true">
        <%= f.fields_for :shootout_microphones, ShootoutMicrophone.new, html: { multipart: true } do |builder| %>
          <div class="input-field col s6">
            <i class="material-icons prefix">mic</i>
            <%= builder.select :microphone_id, @microphones.collect { |mic| [ mic.manufacturer.name + " " + mic.model, mic.id ] }, prompt: 'Choose a Mic'  %>
          </div>
          <div class="input-field col s5">
            <i class="material-icons prefix">hearing</i>
            <%= builder.file_field :audio %>
          </div>
          <div class="col s1">
            <button class="remove-shootout-btn">X</button>
          </div>
        <% end %>
    </div>

app/views/partials/_shootout_list.html.erb
<div class="container shootout-container" style="background:url('<%= shootout.instrument.image.url %>'); background-size: cover;">
	<div class="col s12 m12">
        <div class="row current-shootout-header">
            <div class="current-instrument col">
                <%= shootout.instrument.name %>
            </div>        	
            <div class="current-uploader col right">
                <%= link_to shootout.user.username, user_path(shootout.user), class: "uploader-link" %>
            </div>
        </div>
		<div class="row shootout-body">
            <div class="col s3 m3">
                <div class="current-mic row center">
                    <span class="current-mic-manu"><%= shootout.shootout_microphones.first.microphone.manufacturer.name %> <%= shootout.shootout_microphones.first.microphone.model %></span>
                </div>
                <div class="row shootout-mic-image">
                    <%= image_tag shootout.shootout_microphones.first.microphone.image.url, class: "responsive-img current-mic-img" %>
                </div>
            </div>
			<div class="col s9 m9 audiowrap">
                <div class="row">
                    <audio preload class="audio-track" controls="controls" id="shootout-audio-<%= shootout.id %>" onended="hidePause()">
                    <source class="audio-source" src="<%= shootout.shootout_microphones.first.audio.url %>">
                    	Your browser does not support HTML5 Audio!
                    </audio>
                    <div class="playlist-btn choose" hidden>Choose A Microphone To Listen</div>
                    <div class="playlist-btn pause" hidden>Pause<i class="material-icons">pause</i></div>
                </div>
        		<div class="row">
                    <div class="collection shootout-list">
        				<% shootout.shootout_microphones.each do |sm| %>
        				<% mic = sm.microphone %>
                            <div class="row collection-item-row">
                                <p hidden class="collection-item-img-url"><%= mic.image.url %></p>         
                                <a href="#" id="<%= sm.audio.url %>" class="collection-item col waves-effect waves-purple">
                                    <div class="shootout-item" >
                                        <div class="shootout-item-title">
                                            <span class="shootout-item-name">
                                                <%= mic.manufacturer.name %> <%= mic.model %>
                                            </span>
                                        </div>
                                    </div>
                                </a>
                                <div class="col mic-info-btn">
            						<%= link_to '+', microphone_path(mic), class: "btn grey darken-4 go-to-mic-btn" %>
                                </div>
                            </div>
        	            <% end  %>
                    </div>
                    <% if (current_user && current_user != shootout.user) %>            
                        <div class="fav-btn-div col right">
                            <%= form_for (FavShootout.new) do |f| %>
                                <%= f.hidden_field :user_id, value: current_user.id %> 
                                <%= f.hidden_field :shootout_id, value: shootout.id %>
                                <%= f.submit 'Save', class: "fav-btn black right" %>
                            <% end  %>
                        </div>
                    <% end  %>
                </div>
            </div>  
        </div>
	</div>
</div>

app/views/partials/_user_dropdown.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to 'Profile', user_path(current_user) %></li>
  <li><%= link_to "Upload", new_shootout_path %></li>
  <li class="divider"></li>
  <li><%= link_to 'About', pages_about_path %></li>
  <li><%= link_to 'Log Out', destroy_user_session_path, method: "delete" %></li>
</ul>

<ul id="nav-mobile" class="right">
	<li><i class="tiny material-icons person-icon">perm_identity</i></li>
    <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%= current_user.username %><i class="material-icons right">arrow_drop_down</i></a></li>
</ul>